openmpf/openmpf-components

- cpp/CaffeDetection/plugin-files/descriptor/descriptor.json
- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
Adding merge properties to existing components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/3)
> Merge properties

- cpp/CaffeDetection/plugin-files/descriptor/descriptor.json
- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/5)
> Updated component version numbers.

- cpp/CaffeDetection/CMakeLists.txt
- cpp/CaffeDetection/CaffeDetection.cpp
- cpp/CaffeDetection/CaffeDetection.h
- cpp/CaffeDetection/LICENSE
- cpp/CaffeDetection/plugin-files/config/NOTICE
- cpp/CaffeDetection/plugin-files/config/models.cfg
- cpp/CaffeDetection/plugin-files/config/yahoo_nsfw.prototxt
- cpp/CaffeDetection/plugin-files/config/yahoo_nsfw.txt
- cpp/CaffeDetection/plugin-files/descriptor/descriptor.json
- cpp/CaffeDetection/sample_caffe_detector.cpp
- cpp/DlibFaceDetection/CMakeLists.txt
- cpp/DlibFaceDetection/DlibFaceDetection.cpp
- cpp/OalprLicensePlateTextDetection/CMakeLists.txt
- cpp/OalprLicensePlateTextDetection/LicensePlateTextDetection.cpp
- cpp/OcvFaceDetection/CMakeLists.txt
- cpp/OcvFaceDetection/OcvFaceDetection.cpp
- cpp/OcvFaceDetection/test/test_ocv_face_detection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/7)
> Update opencv 3.2

- cpp/CaffeDetection/CaffeDetection.cpp
- cpp/CaffeDetection/CaffeDetection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/10)
> Isolate logic

- cpp/CaffeDetection/plugin-files/descriptor/descriptor.json
- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
Issue #144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/12)
> Add supportsBatchProcessing field to descriptors

- .gitignore
- cpp/DlibFaceDetection/DlibFaceDetection.cpp
- cpp/DlibFaceDetection/DlibFaceDetection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/17)
> Make DlibFace component use frame skipper

- cpp/OalprLicensePlateTextDetection/LicensePlateTextDetection.cpp
- cpp/OalprLicensePlateTextDetection/LicensePlateTextDetection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/19)
> Make Oalpr component use frame skipper

- cpp/OcvFaceDetection/OcvFaceDetection.cpp
- cpp/OcvFaceDetection/OcvFaceDetection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/20)
> Make OcvFace component use frame skipper

- cpp/DlibFaceDetection/CMakeLists.txt
- cpp/DlibFaceDetection/sample_dlib_face_detector.cpp
- cpp/OcvFaceDetection/OcvFaceDetection.cpp
- cpp/OcvFaceDetection/OcvFaceDetection.h
- cpp/OcvFaceDetection/sample_ocv_face_detector.cpp
- cpp/OcvFaceDetection/test/test_ocv_face_detection.cpp
Cleaned up OCV face detection sample binary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/21)
> Renamed OCVFaceDetection to OcvFaceDetection.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/25)
> Update readme develop

- cpp/OalprLicensePlateTextDetection/LicensePlateTextDetection.cpp
- cpp/OalprLicensePlateTextDetection/LicensePlateTextDetection.h
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/27)
> Make OALPR work with feed forward

- cpp/CaffeDetection/CMakeLists.txt
- cpp/CaffeDetection/CaffeDetection.cpp
- cpp/CaffeDetection/plugin-files/descriptor/descriptor.json
- cpp/CaffeDetection/sample_caffe_detector.cpp
- cpp/DlibFaceDetection/CMakeLists.txt
- cpp/OalprLicensePlateTextDetection/CMakeLists.txt
- cpp/OcvFaceDetection/CMakeLists.txt
Fixed Caffe component to use BGR over RGB. Removed transpose property.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/26)
> Updated for OpenCV 3.3.

- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/30)
> Add USE_KEY_FRAMES property to descriptors

- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/33)
> Update USE_KEY_FRAMES description

- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/32)
> Fixed SPHINX SPEECH DETECTION (WITH MARKUP) PIPELINE description.

- java/SphinxSpeechDetection/src/main/java/org/mitre/mpf/detection/sphinx/speech/SphinxSpeechDetectionComponent.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/44)
> Updated Sphinx to use new package name.

- cpp/OalprLicensePlateTextDetection/LicensePlateTextDetection.cpp
- cpp/OcvFaceDetection/OcvFaceDetection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/45)
> Corrected log statement when tracks are found.

- cpp/CaffeDetection/plugin-files/descriptor/descriptor.json
- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/47)
> Updated descriptor file to remove launchArgs.

- cpp/CaffeDetection/CMakeLists.txt
- cpp/DlibFaceDetection/CMakeLists.txt
- cpp/OalprLicensePlateTextDetection/CMakeLists.txt
- cpp/OcvFaceDetection/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/48)
> Update CMakeLists to use new signature for configure_mpf_component.

- cpp/CaffeDetection/plugin-files/descriptor/descriptor.json
- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/pom.xml
- java/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/51)
> Updated version numbers to 2.0.0.

- cpp/DarknetDetection/DarknetDetection.cpp
- cpp/DarknetDetection/DarknetDetection.h
- cpp/DarknetDetection/plugin-files/descriptor/descriptor.json
- cpp/DarknetDetection/test/data/test-whitelist.txt
- cpp/DarknetDetection/test/test_darknet_detection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/55)
> Add support for whitelist to darknet

- cpp/DarknetDetection/CMakeLists.txt
- cpp/DarknetDetection/DarknetDetection.cpp
- cpp/DarknetDetection/DarknetDetection.h
- cpp/DarknetDetection/README.md
- cpp/DarknetDetection/Trackers.h
- cpp/DarknetDetection/darknet_lib/CMakeLists.txt
- cpp/DarknetDetection/darknet_lib/include/darknet.h
- cpp/DarknetDetection/darknet_lib/src/image.h
- cpp/DarknetDetection/darknet_wrapper/CMakeLists.txt
- cpp/DarknetDetection/darknet_wrapper/DarknetImpl.cpp
- cpp/DarknetDetection/darknet_wrapper/DarknetImpl.h
- cpp/DarknetDetection/include/DarknetInterface.h
- cpp/DarknetDetection/plugin-files/descriptor/descriptor.json
- cpp/DarknetDetection/plugin-files/models/models.ini
- cpp/DarknetDetection/sample_darknet_detector.cpp
- cpp/DarknetDetection/test/test_darknet_detection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/58)
> Add CUDA support to Darknet component

- cpp/CMakeLists.txt
- cpp/ComponentSetup.cmake
- cpp/DarknetDetection/darknet_lib/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/60)
> Add a CMake variable for specifying the GPU arch and code options to the nvcc compiler

- cpp/DarknetDetection/darknet_wrapper/DarknetImpl.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/61)
> Blocking sync

- README.md
- cpp/CaffeDetection/LICENSE
- cpp/DarknetDetection/LICENSE
- cpp/DarknetDetection/darknet_lib/LICENSE.mit
- cpp/DlibFaceDetection/LICENSE
- cpp/OalprLicensePlateTextDetection/LICENSE
- cpp/OcvFaceDetection/LICENSE
- java/SphinxSpeechDetection/LICENSE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/62)
> Added Python SDK to README.

- README.md
- cpp/CaffeDetection/plugin-files/descriptor/descriptor.json
- cpp/DarknetDetection/plugin-files/descriptor/descriptor.json
- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/64)
> Add FRAME_RATE_CAP to descriptors

- cpp/CaffeDetection/plugin-files/descriptor/descriptor.json
- cpp/DarknetDetection/plugin-files/descriptor/descriptor.json
- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/pom.xml
- java/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/65)
> Updated version to 2.1.0.

- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/66)
> Added $MPF_HOME/lib to Sphinx ld path env.

- cpp/CaffeDetection/CaffeDetection.cpp
- cpp/DlibFaceDetection/DlibFaceDetection.cpp
- cpp/OalprLicensePlateTextDetection/LicensePlateTextDetection.cpp
- cpp/OcvFaceDetection/OcvFaceDetection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/70)
> Add track level confidence

- cpp/DarknetDetection/DarknetDetection.cpp
- cpp/DarknetDetection/DarknetStreamingDetection.cpp
- cpp/DarknetDetection/darknet_wrapper/DarknetImpl.cpp
- cpp/DarknetDetection/darknet_wrapper/DarknetImpl.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/76)
> Add debug logging to Darknet.

- cpp/SceneChangeDetection/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/79)
> Updated scene change detection README.

- cpp/CaffeDetection/plugin-files/descriptor/descriptor.json
- cpp/DarknetDetection/plugin-files/descriptor/descriptor.json
- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/pom.xml
- java/TikaTextDetection/pom.xml
- java/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/81)
> Updated version to 3.0.0.

- java/TikaImageDetection/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/85)
> Update version number in TikaImageDetection/pom.xml

- java/TikaImageDetection/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/86)
> Update version number in TikaImageDetection/pom.xml (#85)

- cpp/CaffeDetection/plugin-files/descriptor/descriptor.json
- cpp/DarknetDetection/plugin-files/descriptor/descriptor.json
- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/87)
> Track merging is now only applied to videos.

- cpp/DlibFaceDetection/test/test_dlib_face_detection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/93)
> corrected the path to the test output directory in the gtests

- cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/96)
> Update feed forward property descriptions to include REGION.

- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp
- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/98)
> Tesseract component now calls ReverseTransform().

- python/EastTextDetection/east_component/bbox_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/97)
> Fix reported rotation angle to be CCW.

- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp
- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.h
- cpp/TesseractOCRTextDetection/sample_tesseract_ocr_detector.cpp
- cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/100)
>  Tesseract API objects are now stored between GetDetections() calls.

- python/EastTextDetection/Dockerfile
Tested and working in local docker deployment.
https://github.com/openmpf/openmpf/issues/908
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/105)
> Dockerize East Component

- python/EastTextDetection/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/107)
> Refactor docker compose

- cpp/TesseractOCRTextDetection/README.md
- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp
- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.h
- cpp/TesseractOCRTextDetection/plugin-files/config/mpfOCR.ini
- cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json
- cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/111)
> Tesseract remove gibberish filters.

- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/113)
> Resolving image error issues with Tesseract.

- python/EastTextDetection/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/115)
> Remove underscores

- cpp/CaffeDetection/CaffeDetection.cpp
- cpp/DarknetDetection/DarknetDetection.cpp
- cpp/DarknetDetection/DarknetStreamingDetection.cpp
- cpp/DarknetDetection/test/test_darknet_detection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/122)
> Update method names in calls to ModelsIniParser

- java/SphinxSpeechDetection/src/main/java/org/mitre/mpf/detection/sphinx/speech/SphinxSpeechDetectionProcessor.java
- java/SphinxSpeechDetection/src/test/java/org/mitre/mpf/detection/sphinx/speech/TestSphinxSpeechDetectionComponent.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/129)
> Change TRANSCRIPTION to TRANSCRIPT

- cpp/OalprLicensePlateTextDetection/plugin-files/setup/componentSetup.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/137)
> Fix mpf_home usage in Oalpr Ansible file.

- cpp/DarknetDetection/darknet_wrapper/DarknetImpl.cpp
- cpp/DarknetDetection/darknet_wrapper/DarknetImpl.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/136)
> Fix YOLO memory leak.

- cpp/DarknetDetection/darknet_wrapper/DarknetImpl.cpp
- cpp/DarknetDetection/darknet_wrapper/DarknetImpl.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/142)
> hf-merge-master/darknet-memory-leak3

- cpp/DarknetDetection/darknet_wrapper/DarknetImpl.cpp
- cpp/DarknetDetection/darknet_wrapper/DarknetImpl.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/145)
> hf-merge-develop/darknet-memory-leak

- cpp/TesseractOCRTextDetection/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/150)
> Update Tesseract Dockerfile to use new names for ImageMagick yum packages.

- cpp/DarknetDetection/darknet_wrapper/DarknetImpl.cpp
* Fix remaining darknet memory leaks.
* Fix remaining darknet gpu memory leaks.
(cherry picked from commit 43cf34ed71f4ed0451178cb07cd1493ce794a7b8)
(cherry picked from https://github.com/openmpf/openmpf-components/pull/154)
Associated PRs:
- https://github.com/openmpf/openmpf-components/pull/157
- https://github.com/openmpf/openmpf-docker/pull/93
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/157)
> Fix remaining darknet memory leaks. (cherry picked from #154)

- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp
- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/163)
> Fix tesseract memory leak and improve error handling.

- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp
- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.h
- cpp/TesseractOCRTextDetection/plugin-files/config/mpfOCR.ini
- cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json
- cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/170)
> Update Tesseract component to enforce max pixel limits. (#169)

- python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/171)
> Disable segmentation

- python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py
Fixes https://github.com/openmpf/openmpf/issues/1178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/186)
> Fix exception formatting in Azure Speech.

- cpp/TesseractOCRTextDetection/README.md
- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp
- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.h
- cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json
- cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/195)
> Hf merge master/tesseract specify tessdata models

- cpp/TesseractOCRTextDetection/README.md
- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp
- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.h
- cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json
- cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/196)
> hf-merge-develop/tesseract-specify-tessdata-models2

- cpp/TesseractOCRTextDetection/README.md
- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp
- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.h
- cpp/TesseractOCRTextDetection/plugin-files/config/mpfOCR.ini
- cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json
- cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/194)
> Backporting Tesseract MAX_PIXELS setting to 4.1 version. (#1190)

- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/197)
> Hf merge master/tesseract backport max pixels 4.1.x

- cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/198)
> Hf merge develop/tesseract backport max pixels 4.1.x

- cpp/TrtisDetection/Dockerfile
- cpp/TrtisDetection/trtserver_dockerfile/Dockerfile
* Store trtis models in different image and fix s3 build error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/199)
> Feature/trtis model storage (#187)

- cpp/KeywordTagging/KeywordTagging.cpp
- cpp/KeywordTagging/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/204)
> Change detection type to TEXT instead of KEYWORD.

- python/AzureTranslation/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/211)
> Fix algo name in AzureTranslation descriptor

- python/AzureSpeechDetection/README.md
- python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py
- python/AzureSpeechDetection/acs_speech_component/azure_connect.py
- python/AzureSpeechDetection/sample_acs_speech_detector.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/213)
> Retry without diarization when not supported by locale

- python/AzureSpeechDetection/README.md
- python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py
- python/AzureSpeechDetection/acs_speech_component/azure_connect.py
- python/AzureSpeechDetection/sample_acs_speech_detector.py
Merges https://github.com/openmpf/openmpf-components/pull/213 in to develop
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/214)
> hf-merge/diarization

- cpp/DarknetDetection/plugin-files/descriptor/descriptor.json
- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/KeywordTagging/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvDnnDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json
- cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json
- cpp/TrtisDetection/Dockerfile
- cpp/TrtisDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/pom.xml
- java/TikaImageDetection/plugin-files/descriptor/descriptor.json
- java/TikaImageDetection/pom.xml
- java/TikaTextDetection/plugin-files/descriptor/descriptor.json
- java/TikaTextDetection/pom.xml
- java/pom.xml
- python/AzureFormDetection/plugin-files/descriptor/descriptor.json
- python/AzureFormDetection/setup.py
- python/AzureOcrTextDetection/plugin-files/descriptor/descriptor.json
- python/AzureOcrTextDetection/setup.py
- python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json
- python/AzureSpeechDetection/setup.py
- python/AzureTranslation/plugin-files/descriptor/descriptor.json
- python/AzureTranslation/setup.py
- python/EastTextDetection/plugin-files/descriptor/descriptor.json
- python/EastTextDetection/setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/215)
> Update versions to 6.0.

- cpp/TrtisDetection/trtserver_dockerfile/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/218)
> Add TRTIS apt-get update and upgrade.

- python/AzureTranslation/acs_translation_component/acs_translation_component.py
- python/AzureTranslation/tests/test_acs_translation.py
Fixes https://github.com/openmpf/openmpf/issues/1266
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/228)
> Fix bug in guess_breaks

- python/AzureTranslation/README.md
- python/AzureTranslation/acs_translation_component/acs_translation_component.py
- python/AzureTranslation/tests/test_acs_translation.py
Addresses: https://github.com/openmpf/openmpf/issues/1273
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/235)
> Add "SKIPPED TRANSLATION" detection property

- python/AzureTranslation/README.md
- python/AzureTranslation/acs_translation_component/acs_translation_component.py
- python/AzureTranslation/tests/test_acs_translation.py
Merges: https://github.com/openmpf/openmpf-components/pull/235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/236)
> hf-merge/skipped-translation-prop

- python/AzureFormDetection/acs_form_detection_component/acs_form_detection_component.py
- python/AzureOcrTextDetection/acs_ocr_component/acs_ocr_component.py
- python/AzureSpeechDetection/acs_speech_component/acs_speech_component.py
- python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py
- python/AzureSpeechDetection/acs_speech_component/azure_connect.py
- python/AzureTranslation/acs_translation_component/acs_translation_component.py
- python/AzureTranslation/tests/test_acs_translation.py
Merges: https://github.com/openmpf/openmpf-components/pull/237
Associated PRs:
- https://github.com/openmpf/openmpf/pull/1277
- https://github.com/openmpf/openmpf-python-component-sdk/pull/42
- https://github.com/openmpf/openmpf-components/pull/238
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/238)
> hf-merge/azure-retry

- python/AzureTranslation/acs_translation_component/acs_translation_component.py
- python/AzureTranslation/tests/test_acs_translation.py
Fixes: https://github.com/openmpf/openmpf/issues/1284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/240)
> Handle emoji in AzureTranslation

- python/AzureTranslation/acs_translation_component/acs_translation_component.py
- python/AzureTranslation/tests/test_acs_translation.py
Merges: https://github.com/openmpf/openmpf-components/pull/240
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/241)
> hf-merge/translation-emoji

- cpp/DarknetDetection/plugin-files/descriptor/descriptor.json
- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/KeywordTagging/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvDnnDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json
- cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json
- cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json
- cpp/TrtisDetection/Dockerfile
- cpp/TrtisDetection/plugin-files/descriptor/descriptor.json
- cpp/TrtisDetection/trtserver_dockerfile/Dockerfile
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/pom.xml
- java/TikaImageDetection/plugin-files/descriptor/descriptor.json
- java/TikaImageDetection/pom.xml
- java/TikaTextDetection/plugin-files/descriptor/descriptor.json
- java/TikaTextDetection/pom.xml
- java/pom.xml
- python/AzureFormDetection/plugin-files/descriptor/descriptor.json
- python/AzureFormDetection/setup.py
- python/AzureOcrTextDetection/plugin-files/descriptor/descriptor.json
- python/AzureOcrTextDetection/setup.py
- python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json
- python/AzureSpeechDetection/setup.py
- python/AzureTranslation/plugin-files/descriptor/descriptor.json
- python/AzureTranslation/setup.py
- python/EastTextDetection/plugin-files/descriptor/descriptor.json
- python/EastTextDetection/setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/242)
> Update versions to 6.1.

- cpp/DarknetDetection/plugin-files/descriptor/descriptor.json
- cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/KeywordTagging/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvDnnDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json
- cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json
- cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json
- cpp/TrtisDetection/Dockerfile
- cpp/TrtisDetection/plugin-files/descriptor/descriptor.json
- cpp/TrtisDetection/trtserver_dockerfile/Dockerfile
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/pom.xml
- java/TikaImageDetection/plugin-files/descriptor/descriptor.json
- java/TikaImageDetection/pom.xml
- java/TikaTextDetection/plugin-files/descriptor/descriptor.json
- java/TikaTextDetection/pom.xml
- java/pom.xml
- python/AzureFormDetection/plugin-files/descriptor/descriptor.json
- python/AzureFormDetection/setup.py
- python/AzureOcrTextDetection/plugin-files/descriptor/descriptor.json
- python/AzureOcrTextDetection/setup.py
- python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json
- python/AzureSpeechDetection/setup.py
- python/AzureTranslation/plugin-files/descriptor/descriptor.json
- python/AzureTranslation/setup.py
- python/EastTextDetection/plugin-files/descriptor/descriptor.json
- python/EastTextDetection/setup.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1322
- https://github.com/openmpf/openmpf/pull/1321
- https://github.com/openmpf/openmpf-components/pull/253
- https://github.com/openmpf/openmpf-contrib-components/pull/72
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/106
- https://github.com/openmpf/openmpf-python-component-sdk/pull/49
- https://github.com/openmpf/openmpf-java-component-sdk/pull/53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/253)
> Update versions to 6.2.

- cpp/OcvDnnDetection/OcvDnnDetection.cpp
**Issues:**
- https://github.com/openmpf/openmpf/issues/1338
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/255)
> Update OpenCV DNN Detection component to use feed-forward confidences.

- python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/256)
> Add VFR_TARGET_SEGMENT_LENGTH to AzureSpeechDetection

- cpp/OcvYoloDetection/OcvYoloDetection.cpp
- cpp/OcvYoloDetection/Track.cpp
- cpp/OcvYoloDetection/test/test_ocv_yolo_detection.cpp
**Issues:**
- https://github.com/openmpf/openmpf/issues/1308
- https://github.com/openmpf/openmpf/pull/1348
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/258)
> Merge/develop 6.2.2

- README.md
**Issues:**
- https://github.com/openmpf/openmpf/issues/1351
- https://github.com/openmpf/openmpf.github.io/pull/130
- https://github.com/openmpf/openmpf-contrib-components/pull/73
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/259)
> Clarify the difference between Docker and non-Docker behaviors.

- python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py
- python/AzureSpeechDetection/acs_speech_component/azure_connect.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1356
- https://github.com/openmpf/openmpf/issues/1357
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/261)
> Fix error reporting when video file doesn't have audio stream. Handle case where no speaker id is returned.

- python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py
- python/AzureSpeechDetection/acs_speech_component/azure_connect.py
Merges: https://github.com/openmpf/openmpf-components/pull/261
**Issues:**
- https://github.com/openmpf/openmpf/issues/1356
- https://github.com/openmpf/openmpf/issues/1357
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/262)
> hf-merge/azure-speech-wrong-err-code

- cpp/OcvDnnDetection/OcvDnnDetection.cpp
**Issues:**
https://github.com/openmpf/openmpf/issues/1337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/265)
> Hf merge/catch resize error

- cpp/TesseractOCRTextDetection/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1371
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/267)
> Fix build issue by specifying ImageMagick6.

- cpp/TesseractOCRTextDetection/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1371
- https://github.com/openmpf/openmpf-components/pull/267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/268)
> Hf merge/image magick libs

- python/AzureReadTextDetection/plugin-files/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/281)
> Update AzureReadTextDetection to version 6.3.

- cpp/OcvDnnDetection/Dockerfile
- cpp/OcvDnnDetection/OcvDnnDetection.cpp
- cpp/OcvDnnDetection/OcvDnnDetection.h
- cpp/OcvDnnDetection/README.md
- cpp/OcvDnnDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvDnnDetection/plugin-files/models/vehicle_color.pbtxt
- cpp/OcvDnnDetection/plugin-files/models/vehicle_color.txt
- cpp/OcvDnnDetection/test/test_ocv_dnn_detection.cpp
**Issues:**
-https://github.com/openmpf/openmpf/issues/1404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/283)
> Update tensor flow vehicle color model in the OcvDnnDetection component.

- cpp/OcvDnnDetection/plugin-files/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1469
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/289)
> Use "OCV YOLO" tasks for "TENSORFLOW VEHICLE COLOR DETECTION" pipelines.

- cpp/KeywordTagging/CMakeLists.txt
- cpp/OalprLicensePlateTextDetection/CMakeLists.txt
- cpp/OcvDnnDetection/CMakeLists.txt
- cpp/OcvFaceDetection/CMakeLists.txt
- cpp/OcvYoloDetection/CMakeLists.txt
- cpp/OcvYoloDetection/DetectionLocation.cpp
- cpp/OcvYoloDetection/Track.cpp
- cpp/OcvYoloDetection/Track.h
- cpp/SceneChangeDetection/CMakeLists.txt
- cpp/TesseractOCRTextDetection/CMakeLists.txt
- cpp/TrtisDetection/CMakeLists.txt
- cpp/TrtisDetection/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1519
- https://github.com/openmpf/openmpf/pull/1518
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/112
- https://github.com/openmpf/openmpf-docker/pull/165
- https://github.com/openmpf/openmpf-components/pull/293
- https://github.com/openmpf/openmpf-contrib-components/pull/78
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/293)
> Hotfix/ocv 4.5.5

- cpp/KeywordTagging/CMakeLists.txt
- cpp/OalprLicensePlateTextDetection/CMakeLists.txt
- cpp/OcvDnnDetection/CMakeLists.txt
- cpp/OcvFaceDetection/CMakeLists.txt
- cpp/OcvYoloDetection/CMakeLists.txt
- cpp/OcvYoloDetection/DetectionLocation.cpp
- cpp/OcvYoloDetection/Track.cpp
- cpp/OcvYoloDetection/Track.h
- cpp/SceneChangeDetection/CMakeLists.txt
- cpp/TesseractOCRTextDetection/CMakeLists.txt
- cpp/TrtisDetection/CMakeLists.txt
Merges: https://github.com/openmpf/openmpf-components/pull/293
**Issues:**
- https://github.com/openmpf/openmpf/issues/1519
- https://github.com/openmpf/openmpf/pull/1523
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/113
- https://github.com/openmpf/openmpf-docker/pull/166
- https://github.com/openmpf/openmpf-components/pull/294
- https://github.com/openmpf/openmpf-contrib-components/pull/79
- https://github.com/openmpf/openmpf.github.io/pull/150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/294)
> Hf merge/ocv 4.5.5

- python/NlpTextCorrection/tests/test_nlp_correction.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/295)
> Make test_full_suggestions_output more forgiving.

- cpp/KeywordTagging/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvDnnDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json
- cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json
- cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json
- cpp/TrtisDetection/plugin-files/descriptor/descriptor.json
- cpp/TrtisDetection/trtserver_dockerfile/Dockerfile
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/pom.xml
- java/TikaImageDetection/plugin-files/descriptor/descriptor.json
- java/TikaImageDetection/pom.xml
- java/TikaTextDetection/plugin-files/descriptor/descriptor.json
- java/TikaTextDetection/pom.xml
- java/pom.xml
- python/AzureFormDetection/plugin-files/descriptor/descriptor.json
- python/AzureFormDetection/setup.cfg
- python/AzureOcrTextDetection/plugin-files/descriptor/descriptor.json
- python/AzureOcrTextDetection/setup.cfg
- python/AzureReadTextDetection/plugin-files/descriptor/descriptor.json
- python/AzureReadTextDetection/setup.cfg
- python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json
- python/AzureSpeechDetection/setup.cfg
- python/AzureTranslation/plugin-files/descriptor/descriptor.json
- python/AzureTranslation/setup.cfg
- python/EastTextDetection/plugin-files/descriptor/descriptor.json
- python/EastTextDetection/setup.cfg
- python/NlpTextCorrection/plugin-files/descriptor/descriptor.json
- python/NlpTextCorrection/setup.cfg
**Issues:**
- https://github.com/openmpf/openmpf/issues/1634
- https://github.com/openmpf/openmpf/pull/1633
- https://github.com/openmpf/openmpf-components/pull/314
- https://github.com/openmpf/openmpf-contrib-components/pull/85
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/118
- https://github.com/openmpf/openmpf-java-component-sdk/pull/60
- https://github.com/openmpf/openmpf-python-component-sdk/pull/70
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/314)
> Update versions to 7.1.

- cpp/OcvYoloDetection/triton_server/Dockerfile
- java/TikaImageDetection/pom.xml
- java/TikaTextDetection/pom.xml
Merges: https://github.com/openmpf/openmpf-components/pull/315
**Issues:**
- https://github.com/openmpf/openmpf/issues/1635
- https://github.com/openmpf/openmpf/pull/1638
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/316)
> Hf/update versions trivy (#315)

- python/EastTextDetection/east_component/east_processor.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1639
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/317)
> Remove np.bool from east

- python/EastTextDetection/east_component/east_processor.py
Merges: https://github.com/openmpf/openmpf-components/pull/317
**Issues:**
- https://github.com/openmpf/openmpf/issues/1639
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/318)
> Remove np.bool from east (#317)

- python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/319)
> Update missed Azure STT v2.0 logic

- python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py
Merges: https://github.com/openmpf/openmpf-components/pull/319
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/320)
> Update missed Azure STT v2.0 logic #319

- cpp/OcvYoloDetection/triton_server/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1649
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/323)
> Prevent upgrade of cudnn in yolo server dockerfile

- cpp/OcvYoloDetection/triton_server/Dockerfile
Merges: https://github.com/openmpf/openmpf-components/pull/323
**Issues:**
- https://github.com/openmpf/openmpf/issues/1649
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/324)
> Prevent upgrade of cudnn in yolo server dockerfile (#323)

- python/AzureReadTextDetection/README.md
Adding info regarding the Read API v3.2, as well as incoming changes to Azure's Read OCR services. 
Moving forward, we will be looking into testing Read v4.0 as part of the Azure's Computer Vision API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/327)
> Updating Azure Read Detection README (v3.2).

- python/AzureReadTextDetection/README.md
Also including info regarding Azure Read v4.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/328)
> Updating Azure Read Detection README (v3.2). (#327)

- cpp/KeywordTagging/plugin-files/descriptor/descriptor.json
- cpp/OalprLicensePlateTextDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvDnnDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvFaceDetection/plugin-files/descriptor/descriptor.json
- cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json
- cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json
- cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json
- cpp/TrtisDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/plugin-files/descriptor/descriptor.json
- java/SphinxSpeechDetection/pom.xml
- java/TikaImageDetection/plugin-files/descriptor/descriptor.json
- java/TikaImageDetection/pom.xml
- java/TikaTextDetection/plugin-files/descriptor/descriptor.json
- java/TikaTextDetection/pom.xml
- java/pom.xml
- python/AzureFormDetection/plugin-files/descriptor/descriptor.json
- python/AzureFormDetection/setup.cfg
- python/AzureOcrTextDetection/plugin-files/descriptor/descriptor.json
- python/AzureOcrTextDetection/setup.cfg
- python/AzureReadTextDetection/plugin-files/descriptor/descriptor.json
- python/AzureReadTextDetection/setup.cfg
- python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json
- python/AzureSpeechDetection/setup.cfg
- python/AzureTranslation/plugin-files/descriptor/descriptor.json
- python/AzureTranslation/setup.cfg
- python/EastTextDetection/plugin-files/descriptor/descriptor.json
- python/EastTextDetection/setup.cfg
- python/NlpTextCorrection/plugin-files/descriptor/descriptor.json
- python/NlpTextCorrection/setup.cfg
**Issues:**
- https://github.com/openmpf/openmpf/issues/1683
- https://github.com/openmpf/openmpf/pull/1682
- https://github.com/openmpf/openmpf-components/pull/330
- https://github.com/openmpf/openmpf-contrib-components/pull/87
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/120
- https://github.com/openmpf/openmpf-java-component-sdk/pull/62
- https://github.com/openmpf/openmpf-python-component-sdk/pull/75
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/330)
> Update versions to 7.2.

- cpp/KeywordTagging/KeywordTagging.cpp
**Issues:**
- https://github.com/openmpf/openmpf/issues/1695
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/332)
> Fix memory leak in KeywordTagging

- python/ClipDetection/setup.cfg
**Issues:**
- https://github.com/openmpf/openmpf/issues/1735
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/343)
> Lock tritonclient[grpc] version to 2.40

- java/TikaTextDetection/README.md
- java/TikaTextDetection/plugin-files/descriptor/descriptor.json
- java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java
- java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java
- java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java
**Issues:**
- https://github.com/openmpf/openmpf/issues/1768
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/351)
> Add Option to Merge Text Sections in TikaTextDetection.

- cpp/KeywordTagging/CMakeLists.txt
- cpp/OalprLicensePlateTextDetection/CMakeLists.txt
- cpp/OcvDnnDetection/CMakeLists.txt
- cpp/OcvFaceDetection/CMakeLists.txt
- cpp/OcvYoloDetection/CMakeLists.txt
- cpp/SceneChangeDetection/CMakeLists.txt
- cpp/TesseractOCRTextDetection/CMakeLists.txt
- cpp/TrtisDetection/CMakeLists.txt
**Issues:**
- https://github.com/openmpf/openmpf/issues/1785
- https://github.com/openmpf/openmpf/pull/1791
- https://github.com/openmpf/openmpf-docker/pull/211
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/123
- https://github.com/openmpf/openmpf-contrib-components/pull/90
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/362)
> Update build to use OpenCV 4.9.0

- cpp/KeywordTagging/README.md
- python/TransformerTagging/README.md
**Issues:**
- https://github.com/openmpf/openmpf/issues/1808
- https://github.com/openmpf/openmpf.github.io/pull/185
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/368)
> Update "[TAG]" to "<TAG>".

- python/ClipDetection/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1813
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/370)
> Install older version of setuptools

- python/ClipDetection/Dockerfile
Merges: https://github.com/openmpf/openmpf-components/pull/370
**Issues:**
- https://github.com/openmpf/openmpf/issues/1813
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/371)
> Install older version of setuptools (#370)

- python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py
- python/AzureReadTextDetection/plugin-files/descriptor/descriptor.json
- python/AzureReadTextDetection/tests/test_acs.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1834
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/379)
> Make delay in AzureRead configurable and delay before first poll attempt

- python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py
- python/AzureReadTextDetection/plugin-files/descriptor/descriptor.json
- python/AzureReadTextDetection/tests/test_acs.py
Merges: https://github.com/openmpf/openmpf-components/pull/379
**Issues:**
- https://github.com/openmpf/openmpf/issues/1834
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/380)
> Hf merge/azure read delay

- python/AzureTranslation/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1859
- https://github.com/openmpf/openmpf-docker/pull/228
- https://github.com/openmpf/openmpf-components/pull/386
- https://github.com/openmpf/openmpf-python-component-sdk/pull/88
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/386)
> Fix AzureTranslation text splitter install

- python/AzureTranslation/Dockerfile
Merges: https://github.com/openmpf/openmpf-components/pull/386
**Issues:**
- https://github.com/openmpf/openmpf/issues/1859
**Related PRs and MRs:**
- https://github.com/openmpf/openmpf-docker/pull/230
- https://github.com/openmpf/openmpf-components/pull/388
- https://github.com/openmpf/openmpf-python-component-sdk/pull/89
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/388)
> Hf merge/text splitter build

- python/ArgosTranslation/tests/test_argos_translation.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1864
Please review our [Contributor Guide](https://openmpf.github.io/docs/site/Contributor-Guide/index.html).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/389)
> Additional guards for translation errors in the unit test

- python/AzureTranslation/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1865
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/390)
> Copy wtp models to runtime stage

- python/AzureTranslation/Dockerfile
Merges: https://github.com/openmpf/openmpf-components/pull/390
**Issues:**
- https://github.com/openmpf/openmpf/issues/1865
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/391)
> Hf merge/wtp models

- python/ClipDetection/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1931
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/403)
> Fix clip dockerfile
